fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "user_environment",
            "focus_open", "focus_take",
            "window_system_menu",
            "window_chrome_state",
            "scientific_open", "scientific_read", "scientific_close", "scientific_pause", "scientific_stats", "scientific_begin", "scientific_finish", "scientific_validate_slice",
            "binary_open", "binary_read", "binary_close", "binary_search_start", "binary_search_step", "binary_search_cancel", "binary_stats",
            "launch_take", "productivity_read", "productivity_write", "productivity_open", "file_watch", "platform_capabilities", "default_apps", "association_health",
            "document_save",
            "document_create_locations", "document_pick_location", "document_name_available", "document_create",
            "document_reload",
            "document_fingerprint",
            "document_recovery",
            "document_recovery_list",
            "data_sqlite_open",
            "data_sqlite_read",
            "data_sqlite_close",
            "select_path",
            "load_file",
            "read_file_range",
            "file_size",
            "open_file_external",
            "reveal_file",
            "load_related_file",
            "file_revision",
            "decode_image_preview",
            "open_external_url",
            "register_media_source",
            "release_media_source",
            "archive_open",
            "archive_release_entry",
            "archive_list",
            "archive_prepare_entry",
            "archive_read_entry",
            "archive_close",
            "archive_extract",
            "archive_extraction_status",
            "archive_cancel_extraction",
            "archive_resolve_conflict",
        ]),
    ))
    .expect("failed to configure Prism command permissions");
}
