import type { DetectedFileType } from "../../types/files";
export const SAMPLE_LIMIT = 65536;
export const TAIL_LIMIT = 65557;
export const DIRECTORY_LIMIT = 262144;
export const ENTRY_LIMIT = 2048;
export const extensionMap: Readonly<Record<string, DetectedFileType>> = {
  stl: "stl",
  obj: "obj",
  ply: "ply",
  gltf: "gltf",
  glb: "glb",
  step: "step",
  stp: "stp",
  iges: "iges",
  igs: "igs",
  jt: "jt",
  skp: "skp",
  "3dm": "3dm",
  sldprt: "sldprt",
  sldasm: "sldasm",
  catpart: "catpart",
  catproduct: "catproduct",
  fbx: "fbx",
  dae: "dae",
  usd: "usd",
  usda: "usda",
  usdc: "usdc",
  usdz: "usdz",
  "3ds": "3ds",
  c4d: "c4d",
  blend: "blend",
  max: "max",
  dxf: "dxf",
  dwg: "dwg",
  txt: "text",
  log: "text",
  md: "markdown",
  markdown: "markdown",
  mdown: "markdown",
  mkd: "markdown",
  mkdn: "markdown",
  json: "json",
  geojson: "json",
  jsonl: "json",
  ndjson: "json",
  yaml: "yaml",
  yml: "yaml",
  xml: "xml",
  toml: "toml",
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  jsx: "jsx",
  tsx: "tsx",
  py: "python",
  pyw: "python",
  c: "c",
  h: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  java: "java",
  go: "go",
  rs: "rust",
  htm: "html",
  html: "html",
  css: "css",
  csv: "csv",
  tsv: "tsv",
  tab: "tsv",
  mp3: "mp3",
  wav: "wav",
  flac: "flac",
  aac: "aac",
  m4a: "m4a",
  ogg: "ogg",
  opus: "opus",
  wma: "wma",
  aiff: "aiff",
  mp4: "mp4",
  webm: "webm",
  mov: "mov",
  mkv: "mkv",
  avi: "avi",
  mpeg: "mpeg",
  m4v: "m4v",
  epub: "epub",
  eml: "eml",
  msg: "msg",
  aif: "aiff",
  mpg: "mpeg",
  xlsx: "xlsx",
  xlsm: "xlsm",
  xls: "xls",
  xlsb: "xlsb",
  ods: "ods",
  pptx: "pptx",
  pptm: "pptm",
  ppsx: "ppsx",
  potx: "potx",
  ppt: "ppt",
  odp: "odp",
  pdf: "pdf",
  docx: "docx",
  odt: "odt",
  rtf: "rtf",
  doc: "doc",
  png: "png",
  jpg: "jpeg",
  jpeg: "jpeg",
  gif: "gif",
  webp: "webp",
  svg: "svg",
  avif: "avif",
  bmp: "bmp",
  ico: "ico",
  tif: "tiff",
  tiff: "tiff",
  heic: "heic",
  heif: "heif",
  zip: "zip",
  tar: "tar",
  gz: "gz",
  tgz: "tgz",
  rar: "rar",
  bz2: "bz2",
  xz: "xz",
  zst: "zst",
  "7z": "sevenzip",
  parquet: "parquet",
  arrow: "arrow",
  feather: "feather",
  h5: "hdf5",
  hdf5: "hdf5",
  nc: "netcdf",
  netcdf: "netcdf",
  mat: "mat",
  sqlite: "sqlite",
  sqlite3: "sqlite",
  db: "sqlite",
};
export function extensionOf(name: string): string | null {
  if (name.startsWith(".") && !name.slice(1).includes(".")) return null;
  const i = name.lastIndexOf(".");
  return i > 0 && i < name.length - 1 ? name.slice(i + 1).toLowerCase() : null;
}
export const basenameHints: Readonly<Record<string, string>> = {
  dockerfile: "dockerfile",
  makefile: "makefile",
  gnumakefile: "makefile",
  license: "text",
  readme: "text",
  ".gitignore": "gitignore",
  ".env": "env",
};
export const binaryTypes = new Set<DetectedFileType>([
  "mp3",
  "wav",
  "flac",
  "aac",
  "m4a",
  "ogg",
  "opus",
  "wma",
  "aiff",
  "mp4",
  "webm",
  "mov",
  "mkv",
  "avi",
  "mpeg",
  "m4v",
  "epub",
  "msg",
  "xlsx",
  "xlsm",
  "xls",
  "xlsb",
  "ods",
  "pptx",
  "pptm",
  "ppsx",
  "potx",
  "ppt",
  "odp",
  "pdf",
  "docx",
  "odt",
  "doc",
  "png",
  "jpeg",
  "gif",
  "webp",
  "avif",
  "bmp",
  "ico",
  "tiff",
  "heic",
  "heif",
  "zip",
  "tar",
  "gz",
  "tgz",
  "sevenzip",
  "rar",
  "bz2",
  "xz",
  "zst",

  "parquet",
  "arrow",
  "feather",
  "hdf5",
  "netcdf",
  "mat",
  "sqlite",
  "binary",
]);
export const mimeMap: Readonly<Partial<Record<DetectedFileType, string>>> = {
  text: "text/plain",
  markdown: "text/markdown",
  json: "application/json",
  yaml: "application/yaml",
  xml: "application/xml",
  toml: "application/toml",
  javascript: "text/javascript",
  typescript: "text/typescript",
  jsx: "text/plain",
  tsx: "text/plain",
  python: "text/plain",
  c: "text/plain",
  cpp: "text/plain",
  java: "text/plain",
  go: "text/plain",
  rust: "text/plain",
  html: "text/html",
  css: "text/css",
  csv: "text/csv",
  tsv: "text/tab-separated-values",
  mp3: "audio/mpeg",
  wav: "audio/wav",
  flac: "audio/flac",
  aac: "audio/aac",
  m4a: "audio/mp4",
  ogg: "audio/ogg",
  opus: "audio/opus",
  wma: "audio/x-ms-wma",
  aiff: "audio/aiff",
  mp4: "video/mp4",
  webm: "video/webm",
  mov: "video/quicktime",
  mkv: "video/x-matroska",
  avi: "video/x-msvideo",
  mpeg: "video/mpeg",
  m4v: "video/mp4",
  epub: "application/epub+zip",
  eml: "message/rfc822",
  msg: "application/vnd.ms-outlook",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  xlsm: "application/vnd.ms-excel.sheet.macroEnabled.12",
  xls: "application/vnd.ms-excel",
  xlsb: "application/vnd.ms-excel.sheet.binary.macroEnabled.12",
  ods: "application/vnd.oasis.opendocument.spreadsheet",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  pptm: "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
  ppsx: "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
  potx: "application/vnd.openxmlformats-officedocument.presentationml.template",
  ppt: "application/vnd.ms-powerpoint",
  odp: "application/vnd.oasis.opendocument.presentation",
  pdf: "application/pdf",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  odt: "application/vnd.oasis.opendocument.text",
  rtf: "application/rtf",
  doc: "application/msword",
  png: "image/png",
  jpeg: "image/jpeg",
  gif: "image/gif",
  webp: "image/webp",
  svg: "image/svg+xml",
  avif: "image/avif",
  bmp: "image/bmp",
  ico: "image/x-icon",
  tiff: "image/tiff",
  heic: "image/heic",
  heif: "image/heif",
  zip: "application/zip",
  tar: "application/x-tar",
  gz: "application/gzip",
  tgz: "application/gzip",
  sevenzip: "application/x-7z-compressed",
  rar: "application/vnd.rar",
  bz2: "application/x-bzip2",
  xz: "application/x-xz",
  zst: "application/zstd",

  parquet: "application/vnd.apache.parquet",
  arrow: "application/vnd.apache.arrow.file",
  feather: "application/vnd.apache.arrow.file",
  hdf5: "application/x-hdf5",
  netcdf: "application/x-netcdf",
  mat: "application/x-matlab-data",
  sqlite: "application/vnd.sqlite3",
};
export function typeFromMime(mime: string): DetectedFileType | null {
  const value = mime.split(";")[0].trim().toLowerCase();
  if (value === "text/plain" || value === "application/octet-stream")
    return null;
  if (value === "application/geo+json" || value === "text/json") return "json";
  return (
    (Object.entries(mimeMap).find(([, m]) => m === value)?.[0] as
      DetectedFileType | undefined) ??
    (
      {
        "application/x-zip-compressed": "zip",
        "application/javascript": "javascript",
        "text/xml": "xml",
      } as Record<string, DetectedFileType>
    )[value] ??
    null
  );
}
