import {describe,it,expect,afterEach,vi} from 'vitest';
import {render,screen,fireEvent,act} from '@testing-library/react';
import {supportedLanguages,catalogs,t,setUiLanguage,resolveLanguage,uiLanguage} from '../src/i18n';
import {browserEnvironment,mergeEnvironment,canonicalLocale,getUserEnvironment} from '../src/platform/user-environment';
import {NewFileDialog} from '../src/document/NewFileDialog';
import {ViewerError} from '../src/viewer/core/errors';
import {validateUiSettings} from '../src/platform/ui-settings';
import {readFileSync} from 'node:fs';
afterEach(()=>{act(()=>setUiLanguage('en',false));localStorage.removeItem('elorin-ui-language');});
describe('System environment and language selection',()=>{
 it.each([['zh-TW','zh'],['en-GB','en'],['ja-JP','ja'],['ko-KR','ko'],['it-IT','it'],['fr-CA','fr'],['pt-BR','pt']] as const)('resolves %s to %s', (tag,expected)=>{expect(resolveLanguage([tag])).toBe(expected);});
 it('uses supported preferred languages and falls back predictably',()=>{expect(resolveLanguage(['de-DE','ja-JP','en-US'])).toBe('ja');expect(resolveLanguage(['de-DE'])).toBe('en');expect(canonicalLocale('pt_BR')).toBe('pt-BR');expect(canonicalLocale('broken@tag')).toBeUndefined();});
 it('reads OS language independently of regional format and retains IANA time zone',()=>{const browser={...browserEnvironment(),locale:'en-US',preferredLanguages:['en-US'],timeZone:'Asia/Shanghai'};const env=mergeEnvironment(browser,{locale:'it-IT',preferredLanguages:['ja-JP','en-US'],region:'JP',windowsTimeZone:'Tokyo Standard Time'});expect(env).toMatchObject({locale:'it-IT',defaultLanguage:'ja-JP',region:'JP',timeZone:'Asia/Shanghai',windowsTimeZone:'Tokyo Standard Time',source:'system'});expect(env.preferredLanguages).toEqual(['ja-JP','en-US']);});
 it('uses native regional locale when the native language list is empty',()=>{const env=mergeEnvironment(browserEnvironment(),{locale:'ko-KR'});expect(env.defaultLanguage).toBe('ko-KR');expect(env.preferredLanguages).toEqual(['ko-KR']);});
 it('returns defensive language arrays from its cached public API',async()=>{const first=await getUserEnvironment();const original=[...first.preferredLanguages];first.preferredLanguages.push('xx');expect((await getUserEnvironment()).preferredLanguages).toEqual(original);});
 it('persists explicit choice and exposes document language',()=>{setUiLanguage('fr');expect(localStorage.getItem('elorin-ui-language')).toBe('fr');expect(uiLanguage()).toBe('fr');expect(document.documentElement.lang).toBe('fr');setUiLanguage('zh',false);expect(document.documentElement.lang).toBe('zh-CN');});
 it('validates all seven preferences while retaining other user settings',()=>{for(const language of [...supportedLanguages,'system'])expect(validateUiSettings({language,accent:'#6256ff',statusBar:'hide'})).toMatchObject({language,accent:'#6256ff',statusBar:'hide'});expect(validateUiSettings({language:'bogus'}).language).toBe('system');});
});
describe('Complete translation catalogues and actual UI',()=>{
 it('has six complete catalogues with identical keys and intact dynamic parameters',()=>{const keys=Object.keys(catalogs.zh);expect(keys.length).toBeGreaterThan(1400);const placeholders=(s:string)=>[...s.matchAll(/\{(\w+)\}/g)].map(x=>x[1]).sort();for(const code of supportedLanguages.filter(c=>c!=='en')){expect(Object.keys(catalogs[code]).sort()).toEqual([...keys].sort());for(const key of keys){expect(catalogs[code][key].trim(),`${code}: ${key}`).not.toBe('');expect(placeholders(catalogs[code][key]),`${code}: ${key}`).toEqual(placeholders(key));}}});
 it('covers every translated runtime literal, including accessible names',()=>{const inventory=JSON.parse(readFileSync('docs/qa/i18n/strings.json','utf8')) as {text:string}[];for(const {text} of inventory)for(const code of supportedLanguages.filter(c=>c!=='en'))expect(catalogs[code][text],`${code}: ${text}`).toBeDefined();});
 it.each(supportedLanguages)('changes the live new-file UI to %s without replacing the typed file name',(code)=>{act(()=>setUiLanguage('en',false));render(<NewFileDialog onClose={vi.fn()} onCreate={vi.fn()} />);fireEvent.change(screen.getByLabelText('File name'),{target:{value:'User Open File 日本語'}});act(()=>setUiLanguage(code,false));expect(screen.getByRole('heading',{name:t('New File',undefined,code)})).toBeInTheDocument();expect(screen.getByLabelText(t('File name',undefined,code))).toHaveValue('User Open File 日本語');fireEvent.change(screen.getByLabelText(t('File name',undefined,code)),{target:{value:'../bad'}});expect(screen.getByRole('alert')).toHaveTextContent(t('Use a file name without reserved characters or a trailing dot or space.',undefined,code));expect(screen.getByRole('button',{name:t('Create',undefined,code)})).toBeDisabled();});
 it.each(supportedLanguages)('localizes recovery in %s while retaining native error codes and detail',(code)=>{setUiLanguage(code,false);const error=ViewerError.from({code:'PERMISSION_DENIED',message:'Access denied: User Open File.txt'});expect(error.userMessage).toBe(t('没有读取权限，请检查授权后重新打开。',undefined,code));expect(error.code).toBe('PERMISSION_DENIED');expect(error.message).toBe('Access denied: User Open File.txt');});
 it('translates raw runtime status without changing the status used by search logic',()=>{setUiLanguage('zh',false);expect(t('Match at 0xFF00')).toBe('匹配位置 0xFF00');expect(t('Searching at 256 / 1024 bytes')).toBe('正在搜索 256 / 1024 字节');expect(t('User Open File 日本語')).toBe('User Open File 日本語');});
 it('keeps path and numeric parameters intact',()=>{for(const code of supportedLanguages){const result=t('Selected 0x{v0} · Cache {v1} / {v2} bytes',{v0:'FF00',v1:256,v2:1024},code);expect(result).toContain('FF00');expect(result).toContain('256');expect(result).toContain('1024');expect(result).not.toMatch(/\{v\d\}/);}});
});


