import { describe, it, expect, vi, afterEach } from 'vitest';
import { render, fireEvent, screen, waitFor, cleanup } from '@testing-library/react';
import { BinaryModel, ascii, decimal, hex, parseOffset, searchPattern, validRange, type BinaryBackend } from '../src/viewer/plugins/hex/binary-model';
import { inspectBytes } from '../src/viewer/plugins/hex/byte-inspector';
import { HexViewer, ByteInspector } from '../src/viewer/plugins/hex/HexViewer';
import { createBuiltinRegistry } from '../src/viewer/builtins';
import { bindFileSource, type FileSource } from '../src/services/fileSource';
import { VirtualFileSource } from '../src/vfs/VirtualFileSource';
import { ViewerController } from '../src/viewer/core/controller';
import type { ViewerRenderProps, ViewerState } from '../src/viewer/core/types';
import { input } from './viewer-helpers';
afterEach(cleanup);
function source(size=100000): FileSource { return { getSize:vi.fn(async()=>size),readRange:vi.fn(async(at,n)=>Uint8Array.from({length:Math.min(n,size-at)},(_,i)=>(at+i)%256)),readAll:vi.fn(async()=>{throw Error('Forbidden whole-file read');}),readText:vi.fn(async()=>{throw Error('Forbidden text read');}) }; }
function props(model:BinaryModel):ViewerRenderProps<BinaryModel>{return {model,context:{...input(),signal:model.signal,onCleanup:vi.fn()},session:{metadata:{}},updateSession:vi.fn()};}
function backend(overrides:Partial<BinaryBackend>={}):BinaryBackend{return {open:vi.fn(async()=>({id:'session',size:'100000',remote:false})),read:vi.fn(async(_id,at,n)=>Uint8Array.from({length:n},(_,i)=>Number((BigInt(at)+BigInt(i))%256n))),close:vi.fn(async()=>{}),start:vi.fn(async()=> 'token'),step:vi.fn(async()=>({status:'done' as const,cursor:'100000'})),cancel:vi.fn(async()=>{}),...overrides};}
describe('Module 18 exact addressing and byte interpretation',()=>{
 it.each(['-1','1.2','1e3','',' 1','18446744073709551616'])('rejects invalid offset %s',value=>expect(()=>decimal(value)).toThrow());
 it('keeps u64 offsets precise through optional source and bound source',async()=>{const s=source();s.getSize64=async()=> '9007199254741100';s.readRange64=vi.fn(async(at,n)=>Uint8Array.from({length:n},(_,i)=>Number((BigInt(at)+BigInt(i))%256n)));const m=await BinaryModel.open(bindFileSource(s,new AbortController().signal),new AbortController().signal,65536);expect((await m.read(9007199254740993n,1))[0]).toBe(1);expect(s.readRange64).toHaveBeenCalledWith('9007199254740992',108);expect(s.readRange).not.toHaveBeenCalled();m.dispose();});
 it('limits requests and catches u64 addition overflow',()=>{expect(()=>validRange((1n<<64n)-1n,(1n<<64n)-1n,1)).toThrow();expect(()=>validRange(1n,2n,0)).toThrow();expect(()=>validRange(100n,0n,1048577)).toThrow();expect(parseOffset('0xFFFFFFFFFFFFFFFF')).toBe((1n<<64n)-1n);});
 it('rejects imprecise legacy source size rather than copying it',async()=>await expect(BinaryModel.open(source(Number.MAX_SAFE_INTEGER+1),new AbortController().signal)).rejects.toThrow(/precise/));
 it('maps each byte to one printable ASCII or placeholder',()=>{expect(ascii(0)).toBe('·');expect(ascii(255)).toBe('·');expect(ascii(65)).toBe('A');expect(hex(new Uint8Array([0,0xde,255]))).toBe('00 DE FF');});
 it('reads exact range and never reads all',async()=>{const s=source(),m=await BinaryModel.open(s,new AbortController().signal);expect(Array.from(await m.read(255n,3))).toEqual([255,0,1]);expect(s.readAll).not.toHaveBeenCalled();m.dispose();});
 it('uses exact signed and unsigned bigint values and endian order',()=>{const bytes=new Uint8Array(8).fill(255),v=inspectBytes(bytes,true);expect(v.UInt64).toBe('18446744073709551615');expect(v.Int64).toBe('-1');expect(v.Int8).toBe('-1');expect(inspectBytes(new Uint8Array([1,2]),true).UInt16).toBe('513');expect(inspectBytes(new Uint8Array([1,2]),false).UInt16).toBe('258');});
 it('interprets Float32/64, NaN, infinity and negative zero',()=>{const b=new Uint8Array(8),d=new DataView(b.buffer);d.setFloat64(0,Math.PI,true);expect(inspectBytes(b,true).Float64).toBe(String(Math.PI));d.setFloat32(0,Infinity,true);expect(inspectBytes(b,true).Float32).toBe('Infinity');d.setFloat32(0,NaN,true);expect(inspectBytes(b,true).Float32).toBe('NaN');d.setFloat32(0,-0,true);expect(inspectBytes(b,true).Float32).toBe('-0');});
 it('does not pad partial types or malformed UTF-8',()=>{const v=inspectBytes(new Uint8Array([0xff]),true);expect(v.UInt16).toBe('Unavailable');expect(v.UInt64).toBe('Unavailable');expect(v['UTF-8 preview']).toBe('Invalid or incomplete UTF-8');expect(v['Binary bits']).toBe('11111111');expect(inspectBytes(new Uint8Array(),true).UInt8).toBe('Unavailable');});
});
describe('Module 18 bounded lifecycle and routing',()=>{
 it('rejects a closed native VFS lease before serving cached bytes',async()=>{const v=new VirtualFileSource(source(),'native-entry',1,['zip','bin']);const b=backend(),m=await BinaryModel.open(v,new AbortController().signal,65536,b);await m.read(0n,1);v.dispose();await expect(m.read(0n,1)).rejects.toThrow(/closed/);m.dispose();});
 it('opens raw bytes even when the specialized format adapter rejects them',async()=>{const registry=createBuiltinRegistry(),value=input();value.file={...value.file,detectedType:'json',isText:false,isBinary:true,format:{formatId:'json',status:'Probable',evidence:[],candidates:['json'],conflict:false,probeBytes:0}};const states:ViewerState[]=[],controller=new ViewerController(registry,s=>states.push(s));controller.start({...value,source:source()},'hex');await waitFor(()=>expect(states.at(-1)).toMatchObject({status:'ready',plugin:{id:'hex'}}));controller.stop();});
 it('enforces and clears the actual cache byte budget',async()=>{const m=await BinaryModel.open(source(8*1048576),new AbortController().signal,131072);for(let i=0;i<16;i++){await m.read(BigInt(i*65536),32);expect(m.cacheBytes).toBeLessThanOrEqual(131072);}m.dispose();expect(m.cacheBytes).toBe(0);});
 it('rejects source revision changes even with cached bytes',async()=>{let revision='one';const s=source();s.getRevision=async()=>revision;const m=await BinaryModel.open(s,new AbortController().signal);await m.read(0n,8);revision='two';await expect(m.read(0n,8)).rejects.toThrow(/changed/);expect(m.cacheBytes).toBe(0);m.dispose();});
 it('discards late reads after cancellation',async()=>{let finish!:(b:Uint8Array)=>void;const s=source();s.readRange=()=>new Promise(r=>finish=r);const signal=new AbortController(),m=await BinaryModel.open(s,signal.signal);const read=m.read(0n,8);signal.abort();finish(new Uint8Array(65536));await expect(read).rejects.toThrow();expect(m.cacheBytes).toBe(0);});
 it('bounds pending transport tasks under rapid jumps',async()=>{const completions:(()=>void)[]=[];const s=source(1024*1048576);let peak=0,active=0;s.readRange=vi.fn(async(_at,n)=>{active++;peak=Math.max(peak,active);await new Promise<void>(r=>completions.push(r));active--;return new Uint8Array(n);});const m=await BinaryModel.open(s,new AbortController().signal);const work=Array.from({length:50},(_,i)=>m.read(BigInt(i*65536),1).catch(()=>undefined));expect(active).toBe(2);while(completions.length){completions.shift()!();await new Promise(r=>setTimeout(r,0));}await Promise.all(work);expect(peak).toBe(2);expect(s.readRange).toHaveBeenCalledTimes(3);m.dispose();});
 it('borrows VFS leases and reports early source closure',async()=>{const released=vi.fn(),v=new VirtualFileSource(source(), 'entry',1,['a.zip','a.bin'],released);const m=await BinaryModel.open(v,new AbortController().signal);await m.read(0n,1);m.dispose();expect(released).not.toHaveBeenCalled();const other=await BinaryModel.open(v,new AbortController().signal);v.dispose();await expect(other.read(65536n,1)).rejects.toThrow(/closed/);other.dispose();expect(released).toHaveBeenCalledOnce();});
 it('checks native access before serving cached bytes and closes once',async()=>{const b=backend(),m=await BinaryModel.open(source(),new AbortController().signal,65536,b);await m.read(0n,1);await m.read(0n,1);expect(b.read).toHaveBeenCalledWith('session','0',0);m.dispose();m.dispose();expect(b.close).toHaveBeenCalledOnce();});
 it('closes a native session if opening finishes after cancellation',async()=>{const abort=new AbortController(),b=backend();b.open=async()=>{abort.abort();return {id:'late',size:'1',remote:false};};await expect(BinaryModel.open(source(),abort.signal,65536,b)).rejects.toThrow();expect(b.close).toHaveBeenCalledWith('late');});
 it('keeps dedicated routes and permits explicit hex for text',async()=>{const registry=createBuiltinRegistry(),file=input().file;expect((await registry.resolve(file,{forceId:'hex'}))?.id).toBe('hex');expect((await registry.resolve({...file,detectedType:'pdf',isText:false,isBinary:true}))?.id).toBe('pdf');expect((await registry.resolve({...file,detectedType:'unknown',isText:false,isBinary:true}))?.id).toBe('core.binary-fallback');});
 it('disposes real binary models when controller switches files',async()=>{const registry=createBuiltinRegistry(),states:ViewerState[]=[],controller=new ViewerController(registry,s=>states.push(s));controller.start({...input(),source:source()},'hex');await waitFor(()=>expect(states.at(-1)?.status).toBe('ready'));const first=(states.at(-1) as Extract<ViewerState,{status:'ready'}>).model as BinaryModel;await first.read(0n,8);controller.start({...input(),source:source()},'hex');await waitFor(()=>expect(first.cacheBytes).toBe(0));controller.stop();});
 it.each([8,16,32])('renders aligned %d-byte rows with bounded DOM',async rows=>{const m=await BinaryModel.open(source(5*1024**3),new AbortController().signal);const p=props(m);p.session.metadata.hexRows=rows;render(<HexViewer {...p}/>);await waitFor(()=>expect(screen.getAllByRole('gridcell')[0].textContent).toBe('00'));expect(screen.getAllByRole('row').length).toBeLessThan(100);const row=screen.getAllByRole('row')[0];expect(row.querySelectorAll('.hex-bytes span').length).toBe(rows);expect(row.querySelectorAll('.hex-ascii span').length).toBe(rows);m.dispose();});
 it('synchronizes selection, keyboard, jump and endian inspector',async()=>{const m=await BinaryModel.open(source(),new AbortController().signal);render(<HexViewer {...props(m)}/>);await waitFor(()=>expect(screen.getAllByRole('gridcell')[0].textContent).toBe('00'));fireEvent.pointerDown(screen.getAllByRole('gridcell')[1]);expect(m.selection()).toBe(1n);const grid=screen.getByRole('grid');fireEvent.keyDown(grid,{key:'ArrowRight'});expect(m.selection()).toBe(2n);fireEvent.change(screen.getByLabelText('Go to offset'),{target:{value:'0x10001'}});fireEvent.click(screen.getByRole('button',{name:'Go'}));expect(m.selection()).toBe(65537n);fireEvent.keyDown(grid,{key:'End',ctrlKey:true});expect(m.selection()).toBe(99999n);cleanup();render(<ByteInspector {...props(m)}/>);await waitFor(()=>expect(screen.getByText('UInt8').nextElementSibling?.textContent).toBe('159'));expect(screen.getAllByText('Unavailable').length).toBeGreaterThan(5);m.dispose();});
 it('stops reads and clears visible data while hidden and resumes',async()=>{const s=source(),m=await BinaryModel.open(s,new AbortController().signal);const p=props(m),view=render(<HexViewer {...p}/>);await waitFor(()=>expect(m.cacheBytes).toBeGreaterThan(0));view.rerender(<HexViewer {...p} context={{...p.context,active:false}}/>);await waitFor(()=>expect(m.cacheBytes).toBe(0));expect(screen.queryAllByRole('row')).toHaveLength(0);expect(screen.getByText('Binary tasks paused.')).toBeTruthy();view.rerender(<HexViewer {...p}/>);await waitFor(()=>expect(screen.getAllByRole('row').length).toBeGreaterThan(0));m.dispose();});
 it('handles zero-byte files without invented bytes',async()=>{const m=await BinaryModel.open(source(0),new AbortController().signal);render(<HexViewer {...props(m)}/>);expect(screen.getByText('Empty file · no bytes to inspect.')).toBeTruthy();expect(screen.queryAllByRole('gridcell')).toHaveLength(0);m.dispose();});
});
describe('Module 18 search transport',()=>{
 it('parses byte hex and explicit UTF-8 only',()=>{expect(Array.from(searchPattern('DE AD BE EF','hex'))).toEqual([222,173,190,239]);expect(Array.from(searchPattern('é','text'))).toEqual([195,169]);for(const bad of ['','D','GG','DEADBEEF','DE X1'])expect(()=>searchPattern(bad,'hex')).toThrow();expect(()=>searchPattern('x'.repeat(4097),'text')).toThrow();});
 it('streams supplied virtual ranges to Rust and yields progress',async()=>{let step=0;const b=backend({open:vi.fn(async()=>({id:'vfs',size:'100000',remote:true})),step:vi.fn(async(_id,_token,bytes)=>{step++;return bytes?{status:'found' as const,offset:'65535',cursor:'65536'}:{status:'need-range' as const,cursor:'0',readOffset:'0',readLength:65537};})});const m=await BinaryModel.open(source(),new AbortController().signal,65536,b),progress=vi.fn();expect(await m.search(new Uint8Array([255,0]),0n,false,new AbortController().signal,progress)).toBe(65535n);expect(step).toBe(2);expect(b.cancel).toHaveBeenCalledWith('vfs','token');m.dispose();});
 it('cancels and rejects late search results',async()=>{const abort=new AbortController(),b=backend({step:vi.fn(async()=>{abort.abort();return {status:'found' as const,offset:'10',cursor:'10'};})});const m=await BinaryModel.open(source(),new AbortController().signal,65536,b);await expect(m.search(new Uint8Array([1]),0n,false,abort.signal,vi.fn())).rejects.toThrow();expect(b.cancel).toHaveBeenCalled();m.dispose();});
 it('reports browser search capability instead of executing JS scans',async()=>{const m=await BinaryModel.open(source(),new AbortController().signal);expect(m.canSearch).toBe(false);await expect(m.search(new Uint8Array([1]),0n,false,new AbortController().signal,vi.fn())).rejects.toThrow(/Rust/);m.dispose();});
});
