import {t} from '../src/i18n';
import {describe,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {readFileSync,writeFileSync} from 'node:fs';
import {ViewerController} from '../src/viewer/core/controller';
import {ViewerRegistry} from '../src/viewer/core/registry';
import {ViewerHost} from '../src/viewer/components/ViewerHost';
import {ViewerError,viewerDiagnosticCode} from '../src/viewer/core/errors';
import {ViewerDiagnostic} from '../src/viewer/components/ViewerDiagnostic';
import {scientificError} from '../src/viewer/plugins/data/errors';
import {type FileSource,bindFileSource} from '../src/services/fileSource';
import {createBuiltinRegistry} from '../src/viewer/builtins';
import {formatManifest,formatIndex,FormatIndex} from '../src/formats';
import {input,testPlugin} from './viewer-helpers';
import type {ViewerState,ViewerContext} from '../src/viewer/core/types';
describe('Module 23 controller contract',()=>{
 it('releases a synchronously throwing plugin once',async()=>{const registry=new ViewerRegistry(),plugin=testPlugin('throw',{load:()=>{throw new SyntaxError('Invalid header');}}),states:ViewerState[]=[];registry.register(plugin);const c=new ViewerController(registry,s=>states.push(s));c.start(input());await vi.waitFor(()=>expect(states.at(-1)?.status).toBe('error'));expect(plugin.dispose).toHaveBeenCalledOnce();c.stop();expect(plugin.dispose).toHaveBeenCalledOnce();});
 it('times out an uncooperative load, releases registered resources, discards/disposes late result',async()=>{let finish!:(v:string)=>void;const cleanup=vi.fn(),plugin=testPlugin('slow',{load:c=>{c.onCleanup(cleanup);return new Promise(r=>finish=r);}}),registry=new ViewerRegistry(),states:ViewerState[]=[];registry.register(plugin);const c=new ViewerController(registry,s=>states.push(s),20);c.start(input());await vi.waitFor(()=>expect(states.at(-1)).toMatchObject({status:'error',error:{code:'OPERATION_TIMEOUT'}}));expect(cleanup).toHaveBeenCalledOnce();finish('late');await vi.waitFor(()=>expect(plugin.dispose).toHaveBeenCalledOnce());expect(states.at(-1)?.status).toBe('error');c.stop();expect(cleanup).toHaveBeenCalledOnce();});
 it('generation and session identity change; borrowed source survives repeated close',async()=>{const contexts:ViewerContext[]=[],file=input(),dispose=vi.fn();(file.source as FileSource).dispose=dispose;const registry=new ViewerRegistry(),plugin=testPlugin('test',{load:async c=>{contexts.push(c);return 'ok';}});registry.register(plugin);const c=new ViewerController(registry,()=>{});c.start(file);await vi.waitFor(()=>expect(contexts.length).toBe(1));c.start(file);await vi.waitFor(()=>expect(contexts.length).toBe(2));expect(contexts[1].generation).toBeGreaterThan(contexts[0].generation!);expect(contexts[1].sessionId).not.toBe(contexts[0].sessionId);expect(contexts[0].signal.aborted).toBe(true);c.stop();c.stop();expect(dispose).not.toHaveBeenCalled();});
 it('late sibling lease closes once without closing its parent',async()=>{let finish!:(v:any)=>void;const source=input().source,child=input().source,release=vi.fn(),parentRelease=vi.fn();(source as FileSource).dispose=parentRelease;(child as FileSource).dispose=release;(source as FileSource).resolveRelated=()=>new Promise(r=>finish=r);const abort=new AbortController(),bound=bindFileSource(source,abort.signal),pending=bound.resolveRelated!('child');abort.abort();finish({file:input().file,source:child});await expect(pending).rejects.toThrow();expect(release).toHaveBeenCalledOnce();expect(parentRelease).not.toHaveBeenCalled();});
});
describe('Module 23 public behavior',()=>{
 it('retains native source-change codes through scientific inline diagnostics',()=>{const error=scientificError({code:'SOURCE_CHANGED',message:'changed'});render(<ViewerDiagnostic error={error}/>);expect(screen.getByRole('alert')).toHaveTextContent(t('读取期间文件发生变化，请重新打开以获取当前内容。'));expect(screen.getByRole('alert')).toHaveTextContent('SOURCE_CHANGED');});
 it('inactive ordinary viewer closes and resumes once, preserving plugin/source scoped preferences',async()=>{const registry=new ViewerRegistry(),plugin=testPlugin('test'),value=input();registry.register(plugin);const view=render(<ViewerHost {...value} registry={registry}/>);await screen.findByText('Model: sample.txt');view.rerender(<ViewerHost {...value} registry={registry} active={false}/>);await screen.findByText(t('查看器已暂停，恢复活动后重新打开。'));expect(plugin.dispose).toHaveBeenCalledOnce();view.rerender(<ViewerHost {...value} registry={registry} active/>);await screen.findByText('Model: sample.txt');expect(plugin.load).toHaveBeenCalledTimes(2);view.rerender(<ViewerHost {...value} registry={registry} active/>);expect(plugin.load).toHaveBeenCalledTimes(2);});
 it('cancel is visible state, not an error; late model cannot restore it',async()=>{let finish!:(v:string)=>void;const registry=new ViewerRegistry(),plugin=testPlugin('test',{load:()=>new Promise(r=>finish=r)});registry.register(plugin);render(<ViewerHost {...input()} registry={registry}/>);await screen.findByRole('button',{name:'Cancel loading'});await waitFor(()=>expect(finish).toBeTypeOf('function'));fireEvent.click(screen.getByRole('button',{name:'Cancel loading'}));expect(screen.getByText(t('加载已取消。'))).toBeInTheDocument();finish('late');await waitFor(()=>expect(plugin.dispose).toHaveBeenCalledOnce());expect(screen.queryByText('Model: late')).not.toBeInTheDocument();expect(screen.queryByRole('alert')).not.toBeInTheDocument();});
 it('permission errors keep native codes and localized recovery with Hex',async()=>{const registry=createBuiltinRegistry();registry.register(testPlugin('broken',{load:async()=>{throw {code:'PERMISSION_DENIED',message:'Access denied: sample'};}}));render(<ViewerHost {...input()} registry={registry}/>);const alert=await screen.findByRole('alert');expect(alert).toHaveTextContent(t('没有读取权限，请检查授权后重新打开。'));expect(alert).toHaveTextContent('PERMISSION_DENIED');expect(alert).toHaveTextContent('Access denied: sample');expect(screen.getByRole('button',{name:'Open as Hex'})).toBeInTheDocument();});
 it('errors distinguish unavailable, changed, cancelled, codec and internal errors',()=>{for(const [code,expected]of [['FILE_NOT_FOUND','SOURCE_UNAVAILABLE'],['READ_FAILED','SOURCE_UNAVAILABLE'],['SOURCE_CLOSED','SOURCE_UNAVAILABLE'],['SOURCE_CHANGED','SOURCE_CHANGED'],['ABORTED','OPERATION_CANCELLED'],['PERMISSION_DENIED','PERMISSION_DENIED'],['OPERATION_TIMEOUT','RESOURCE_LIMIT_EXCEEDED']])expect(ViewerError.from(Object.assign(Error('native original'),{code})).diagnosticCode).toBe(expected);expect(viewerDiagnosticCode(Error('Unsupported codec'))).toBe('CODEC_UNSUPPORTED');expect(viewerDiagnosticCode(Error('Decode failure'))).toBe('DECODE_FAILED');expect(viewerDiagnosticCode(Error('Missing External Resource'))).toBe('SOURCE_UNAVAILABLE');expect(viewerDiagnosticCode(new TypeError('unexpected programming error'))).toBe('INTERNAL_ERROR');});
});
it('audits actual catalogue count and every real registry registration, extension and name rule',()=>{const registry=createBuiltinRegistry(),matrix=JSON.parse(readFileSync('docs/formats/format-capability-matrix.json','utf8'));expect(matrix.formats.length).toBe(formatManifest.length);expect(new Set(formatManifest.map(f=>f.formatId)).size).toBe(formatManifest.length);new FormatIndex(formatManifest);const results=formatManifest.map(c=>{for(const v of c.supportedViews){expect(registry.has(v.viewerId),c.formatId).toBe(true);expect(registry.getById(v.viewerId)?.priority).toBeTypeOf('number');}for(const ext of c.extensions)expect(formatIndex.match('sample.'+ext),ext).toContain(c.formatId);for(const name of c.filenames)if(!name.includes('*'))expect(formatIndex.match(name),name).toContain(c.formatId);expect(registry.has('hex')).toBe(true);return {extensions:c.extensions,special_filenames:c.filenames,detection_rules:c.detectionRules,supported_views:c.supportedViews,fallback:'hex',declared_capabilities:{inspect:c.canInspect,search:c.canSearch,edit:c.canEdit,save:c.canSave,previewLevel:c.previewLevel},format_id:c.formatId,status:'passed',scope:'static registry/detector/capability audit; not content parsing',viewer:c.supportedViews[0].viewerId,priority:registry.getById(c.supportedViews[0].viewerId)?.priority,actual_capability_grade:matrix.formats.find((r:any)=>r.format_id===c.formatId)?.capability_level??null};});writeFileSync('docs/qa/module-23-format-static-audit.json',JSON.stringify({record_count:results.length,results},null,2));});
