import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {decodePsd,psdHeader} from '../src/viewer/plugins/image/image-psd';
import {mat4Adapter} from '../src/viewer/plugins/data/mat4-reader';
import {threeDsAdapter,validateThreeDs} from '../src/viewer/plugins/geometry/three-ds-adapter';
import {resolveSample,magicType} from '../src/services/detection/browserDetector';
import {decodeTiff} from '../src/viewer/plugins/image/image-tiff';
import {enhanceDescriptor,formatIndex} from '../src/formats';
import {createBuiltinRegistry} from '../src/viewer/builtins';
const bytes=(name:string)=>new Uint8Array(readFileSync('tests/fixtures/module28/'+name));
const buffer=(name:string)=>bytes(name).buffer;
const reader=(name:string)=>{const data=bytes(name);return mat4Adapter.parse({size:data.length,read:async(at,n)=>data.slice(at,at+n)});};
describe('Module 28 content adapters',()=>{
 it('big-endian TIFF is decoded as an image, never misidentified as 3DS',()=>{expect(magicType(bytes('big-endian.tiff'))).toBe('tiff');expect(magicType(new Uint8Array([77,77,0,43,0,8,0,0]))).not.toBe('3ds');const image=decodeTiff(buffer('big-endian.tiff'));expect([image.w,image.h]).toEqual([8,8]);expect(Array.from(image.rgba.slice(0,4))).toEqual([0,255,255,255]);});
 for(const name of ['quadrants.psd','quadrants-rle.psd'])it('decodes actual RGB content: '+name,()=>{const image=decodePsd(buffer(name));expect([image.w,image.h]).toEqual([64,64]);const pixel=(x:number,y:number)=>Array.from(image.rgba.slice((y*64+x)*4,(y*64+x)*4+4));expect(pixel(0,0)).toEqual([255,0,0,255]);expect(pixel(63,0)).toEqual([0,255,0,255]);expect(pixel(0,63)).toEqual([0,0,255,255]);expect(pixel(63,63)).toEqual([255,255,255,255]);});
 it('rejects PSD truncation, oversized decode, wrong signature, depth and ZIP before output',()=>{
  expect(()=>decodePsd(buffer('damaged.psd'))).toThrow(/truncated/);expect(()=>decodePsd(buffer('oversized.psd'))).toThrow(/budget/);
  for(const [at,value,message]of [[0,0,'signature'],[4,2,'version'],[22,16,'8-bit']] as const){const data=bytes('quadrants.psd');at===0?data[0]=value:new DataView(data.buffer).setUint16(at,value);expect(()=>psdHeader(data)).toThrow(message);}
  const data=bytes('quadrants.psd');new DataView(data.buffer).setUint16(38,2);expect(()=>decodePsd(data.buffer)).toThrow(/ZIP/);
 });
 it('reads paged Level 4 matrices and complex values without loading whole payload',async()=>{const model=await reader('signals.mat');expect(model.nodes.map(n=>n.name)).toEqual(['signal','complex_signal']);const page=await model.page({node:'matrix:0',start:1,count:2,columns:[0,1]});expect(page.values.map(row=>row.map(c=>c.display))).toEqual([['2.5','20'],['3.75','30']]);const complex=await model.page({node:'matrix:1',start:0,count:2,columns:[0]});expect(complex.values[0][0].raw).toContain('4');expect(complex.values[0][0].raw).toContain('6');expect(page.hasMore).toBe(false);});
 it('reads IEEE big endian MAT and rejects malformed ranges',async()=>{const model=await reader('big-endian.mat');expect((await model.page({node:'matrix:0',start:0,count:2,columns:[0,1]})).values.map(row=>row.map(c=>c.display))).toEqual([['-2','40'],['3','50']]);await expect(model.page({node:'matrix:0',start:-1,count:1,columns:[0]})).rejects.toThrow(/page/);await expect(model.page({node:'matrix:0',start:0,count:129,columns:[0]})).rejects.toThrow(/page/);await expect(reader('damaged.mat')).rejects.toThrow(/payload/);});
 it('does not accept MAT v5/text/sparse as numeric content',async()=>{for(const code of [1,2,2000]){const data=bytes('signals.mat');new DataView(data.buffer).setInt32(0,code,true);await expect(mat4Adapter.parse({size:data.length,read:async(at,n)=>data.slice(at,at+n)})).rejects.toThrow(/Unsupported/);}const data=new TextEncoder().encode('MATLAB 5.0 MAT-file header unsupported');await expect(mat4Adapter.parse({size:data.length,read:async(at,n)=>data.slice(at,at+n)})).rejects.toThrow(/Level 5/);});
 it('decodes genuine 3DS mesh into the existing geometry model',async()=>{const doc=await threeDsAdapter.parse(buffer('tetrahedron.3ds'));expect(doc.category).toBe('scene');expect(doc.metadata.triangles).toBe(4);expect(doc.metadata.vertices).toBe(4);expect(doc.nodes.some(n=>n.name==='tetrahedron')).toBe(true);expect(doc.capabilities.preview).toBe(true);expect(doc.geometry[0].positions).toContain(2);});
 it('refuses corrupt/invalid 3DS and external texture resources before decoder import',()=>{for(const name of ['damaged.3ds','external-texture.3ds'])expect(()=>validateThreeDs(buffer(name))).toThrow(/Corrupted|external textures/);const data=bytes('tetrahedron.3ds');new DataView(data.buffer).setUint32(8,0,true);expect(()=>validateThreeDs(data.buffer)).toThrow(/chunk length/);});
 it('preserves explicit signatures and routes three families through the sole registry',async()=>{const registry=createBuiltinRegistry();for(const [name,format,viewer]of [['quadrants.psd','psd','image'],['signals.mat','mat','scientific'],['tetrahedron.3ds','3ds','scene']] as const){const data=bytes(name),file=enhanceDescriptor(resolveSample(name,data,data.length),data);expect(file.format?.formatId).toBe(format);expect(formatIndex.get(format)?.capabilities.supportedViews[0].viewerId).toBe(viewer);expect((await registry.resolve(file,{forceId:viewer}))?.id).toBe(viewer);}expect(formatIndex.get('npy')?.capabilities.detectionRules?.magic?.[0].bytes).toEqual([147,78,85,77,80,89]);});
 it('signature outranks wrong extension; identification never bypasses parser validation',()=>{const data=bytes('quadrants.psd'),file=enhanceDescriptor(resolveSample('wrong.png',data,data.length),data);expect(file.format?.formatId).toBe('psd');expect(file.format?.status).toBe('Confirmed');const damaged=bytes('damaged.psd');expect(enhanceDescriptor(resolveSample('damaged.psd',damaged,damaged.length),damaged).format?.formatId).toBe('psd');expect(()=>decodePsd(damaged.buffer)).toThrow();});
});
