import { describe, expect, it } from 'vitest';
import { DocumentSession, detectClipboard, EDIT_LIMIT } from '../src/document/session';
import { parseEditableCsv, serializeCsv } from '../src/document/csv';
describe('document sessions', () => {
  it('tracks saved content across undo and redo', () => { const s = new DocumentSession('base', 'text', '/a'); expect(s.dirty).toBe(false); s.modify('edit'); expect(s.dirty).toBe(true); s.undo(); expect(s.dirty).toBe(false); s.redo(); expect(s.dirty).toBe(true); s.saved('edit', 'v2', '/a'); expect(s.dirty).toBe(false); s.undo(); expect(s.dirty).toBe(true); s.redo(); expect(s.dirty).toBe(false); });
  it('keeps transactions and histories independent', () => { const a = new DocumentSession('', 'text'), b = new DocumentSession('', 'text'); a.modify('large paste'); b.modify('other'); a.undo(); expect(a.currentState).toBe(''); expect(b.currentState).toBe('other'); });
  it('preserves source precision, BOM and newlines', () => { const source = '{\r\n "n": 900719925474099312345\r\n}'; const s = new DocumentSession(source, 'json', '/a', null, true); expect(s.validationState).toBeNull(); expect(s.lineEndings).toBe('CRLF'); expect(new TextDecoder('utf8', { ignoreBOM: true }).decode(s.serialize())).toBe('\uFEFF' + source); });
  it('reports JSON diagnostics without changing source', () => { const s = new DocumentSession('{\n "x":\n}', 'json'); expect(s.validationState?.line).toBe(3); expect(s.currentState).toBe('{\n "x":\n}'); });
  it('guards memory before modifying', () => { const s = new DocumentSession('base', 'text'); expect(() => s.modify('x'.repeat(EDIT_LIMIT + 1))).toThrow(); expect(s.currentState).toBe('base'); });
  it('restores exact saved revisions on undo/redo', () => { const s = new DocumentSession('base','text','/a'); s.modify('edit'); s.saved('edit','v2','/a'); const saved = s.savedRevision; s.undo(); expect(s.revision).not.toBe(saved); s.redo(); expect(s.revision).toBe(saved); });
  it('groups IME composition into one transaction', () => { const s = new DocumentSession('','text'); s.beginTransaction(); s.modify('中'); s.modify('中文👋'); s.endTransaction(); s.undo(); expect(s.currentState).toBe(''); s.redo(); expect(s.currentState).toBe('中文👋'); });
  it('guards UTF-8 byte size, not only character count', () => { const s = new DocumentSession('base','text'); expect(()=>s.modify('中'.repeat(EDIT_LIMIT / 2))).toThrow(); expect(s.currentState).toBe('base'); });
  it.each([['a;b\r\n00123;"a;\"\"b\"\""\r\n',false],['a\tb\n00123\t"line one\nline two"\n',true],['a,b,c\n1,2\n3,4,5,6\n',false],['a,a\n00123,=cmd|x',false]])('round-trips CSV raw values and dialect %s', (text, tab) => { const parsed = parseEditableCsv(text,tab); const saved = serializeCsv(parsed.rows, parsed.dialect.delimiter, parsed.dialect.newline, /[\r\n]$/.test(text)); expect(parseEditableCsv(saved,tab).rows).toEqual(parsed.rows); });
  it('distinguishes an empty CSV from an empty row', () => { expect(parseEditableCsv('').rows).toEqual([]); expect(parseEditableCsv(serializeCsv([['']],',','\n',false)).rows).toEqual([['']]); });
  it('preserves CSV schema in undo transactions', () => { const s = new DocumentSession('a,b\n1,2','csv','/a'); s.csvColumns=2; s.csvHeader=true; s.modify('a\n1',{columns:1,header:true}); s.undo(); expect(s.csvColumns).toBe(2); s.redo(); expect(s.csvColumns).toBe(1); });
  it.each([['{}','json'],['a,b\nc,d','csv'],['a\tb\nc\td','csv'],['# Title','markdown'],['hello','text'],['','text'],['https://example.org','text']])('detects clipboard %s', (text, kind) => expect(detectClipboard(text)).toBe(kind));
});
