import { describe,it,expect,vi } from 'vitest';
import { PlaybackController } from '../src/viewer/plugins/media/PlaybackController';
import { SourceTokenizer } from '../src/viewer/plugins/media/media-probe';
import type { ViewerContext } from '../src/viewer/core/types';
import { ViewerError,classifyViewerFailure } from '../src/viewer/core/errors';
import { readFileSync } from 'node:fs';
import { NpyReader } from '../src/viewer/plugins/data/npy-reader';
import { parseSubtitles } from '../src/viewer/plugins/media/subtitles';
import { sampleWaveform } from '../src/viewer/plugins/media/waveform';
import { MemoryFileSource } from '../src/services/fileSource';
import { detectFileSource } from '../src/services/detection/browserDetector';
import { formatIndex } from '../src/formats';
const bytes=(name:string)=>readFileSync('test-fixtures/advanced22/'+name);
async function npy(name:string){const b=bytes(name);let reads=0;const r=new NpyReader(async(at,n)=>{reads+=n;return new Uint8Array(b.subarray(at,at+n));},b.length);await r.open();return {r,reads:()=>reads};}
describe('Module 22 scientific additions',()=>{
 it('reads the tail of a simulated 8 GiB NPY without allocating its payload',async()=>{const shape=2**31,header=`{'descr': '<i4', 'fortran_order': False, 'shape': (${shape},), }\n`,head=new Uint8Array(10+header.length);head.set([147,78,85,77,80,89,1,0]);new DataView(head.buffer).setUint16(8,header.length,true);head.set(new TextEncoder().encode(header),10);let allocated=0;const r=new NpyReader(async(at,n)=>{allocated+=n;if(at<head.length)return head.slice(at,at+n);const b=new Uint8Array(n);new DataView(b.buffer).setInt32(0,123456,true);return b;},head.length+shape*4);await r.open();const p=await r.page({node:'array',start:shape-1,count:1,columns:[0]});expect(p.values[0][0].raw).toBe('123456');expect(allocated).toBeLessThan(1024);});
 it('reads multidimensional slices without reading full payload',async()=>{const {r}=await npy('matrix.npy');const p=await r.page({node:'array',start:0,count:3,columns:[0,3],fixed:[1]});expect(p.values.map(v=>v.map(c=>c.raw))).toEqual([['12','15'],['16','19'],['20','23']]);});
 it('reads Fortran order and big endian',async()=>{const {r}=await npy('fortran.npy');const p=await r.page({node:'array',start:0,count:3,columns:[0,3]});expect(p.values.map(v=>v.map(c=>c.raw))).toEqual([['0','3'],['4','7'],['8','11']]);});
 it('keeps int64 exact, scalar and empty arrays',async()=>{const {r}=await npy('int64.npy');const p=await r.page({node:'array',start:0,count:2,columns:[0]});expect(p.values.map(v=>v[0].raw)).toEqual(['9223372036854775807','-9223372036854775808']);const scalar=(await npy('scalar.npy')).r;expect((await scalar.page({node:'array',start:0,count:1,columns:[0]})).values[0][0].raw).toBe('3.25');expect((await (await npy('empty.npy')).r.page({node:'array',start:0,count:1,columns:[0]})).values).toEqual([]);});
 it('handles complex/float16 and special values',async()=>{const c=(await npy('complex.npy')).r;expect((await c.page({node:'array',start:0,count:2,columns:[0]})).values[0][0].details).toEqual({real:'3',imaginary:'4'});const r=(await npy('half.npy')).r;expect((await r.page({node:'array',start:0,count:5,columns:[0]})).values.map(v=>v[0].raw)).toEqual(['0','-0.0','1.5','NaN','+∞']);});
 it('rejects object/pickle without reading payload',async()=>{const b=bytes('object.npy');let maxRead=0;const r=new NpyReader(async(at,n)=>{maxRead=Math.max(maxRead,at+n);return new Uint8Array(b.subarray(at,at+n));},b.length);await expect(r.open()).rejects.toThrow('pickle');expect(maxRead).toBeLessThan(b.length);});
 it('rejects forged dimensions, truncation and illegal indices',async()=>{const b=bytes('matrix.npy');const r=new NpyReader(async(at,n)=>new Uint8Array(b.subarray(at,at+n)),b.length-1);await expect(r.open()).rejects.toThrow('payload length');const valid=(await npy('matrix.npy')).r;await expect(valid.page({node:'array',start:0,count:1,columns:[4],fixed:[0]})).rejects.toThrow();await expect(valid.page({node:'array',start:0,count:1,columns:[0],fixed:[2]})).rejects.toThrow();});
 it('routes NPY/NPZ via existing format adapters',async()=>{for(const [file,viewer] of [['matrix.npy','scientific'],['arrays.npz','archive']]){const source=new MemoryFileSource(new Blob([bytes(file)]));const descriptor=await detectFileSource(file,source);const adapter=formatIndex.get(descriptor.format!.formatId)!;const doc=await adapter.open(source,{file:descriptor,signal:new AbortController().signal,onCleanup:()=>{}});expect(doc.view.viewerId).toBe(viewer);}});
});
it('suspends/releases media source, restores time without autoplay and cleans listeners',async()=>{const e=document.createElement('audio');e.src='https://example.invalid/authorized.wav';e.currentTime=7;e.pause=vi.fn();e.load=vi.fn();e.play=vi.fn(async()=>{});const p=new PlaybackController(e);p.suspend();expect(e.hasAttribute('src')).toBe(false);await p.play();expect(e.play).not.toHaveBeenCalled();p.resume();e.dispatchEvent(new Event('loadedmetadata'));expect(e.currentTime).toBe(7);expect(e.play).not.toHaveBeenCalled();p.suspend();p.dispose();expect(e.hasAttribute('src')).toBe(false);p.resume();expect(e.hasAttribute('src')).toBe(false);});
it('rejects oversized tokenizer tokens before allocation or source access',async()=>{const read=vi.fn(),t=new SourceTokenizer({file:{size:100},source:{readRange:read},signal:new AbortController().signal} as unknown as ViewerContext);await expect(t.peekToken({len:2**40,get:()=>0})).rejects.toThrow('budget');await expect(t.readToken({len:-1,get:()=>0})).rejects.toThrow('budget');expect(read).not.toHaveBeenCalled();});
it('keeps original error details and distinct diagnostic categories',()=>{for(const [message,category] of [['Not recognized','NotRecognized'],['Recognized but Unsupported','RecognizedButUnsupported'],['Unsupported codec','CodecUnsupported'],['Missing External Resource','MissingExternalResource'],['Corrupted File','CorruptedFile'],['Invalid Structure','InvalidStructure'],['Resource Limit Exceeded','ResourceLimitExceeded'],['Permission denied','PermissionDenied'],['Cancelled','Cancelled'],['Source Changed','SourceChanged'],['Decode failure','DecodeFailure'],['Renderer unavailable','RendererUnavailable']])expect(classifyViewerFailure(Error(message))).toBe(category);const original=Object.assign(Error('source revision differs'),{code:'SOURCE_CHANGED'});const wrapped=ViewerError.from(original);expect(wrapped.message).toBe(original.message);expect(wrapped.code).toBe('SOURCE_CHANGED');expect(wrapped.detail).toBe(original);expect(ViewerError.from(new SyntaxError('bad token at 17')).message).toBe('bad token at 17');});
describe('Module 22 subtitles',()=>{
 it('preserves BOM Unicode multiline and overlap warnings',()=>{const d=parseSubtitles(bytes('example.srt').toString('utf8'),'srt');expect(d.cues[0].text).toBe('科研 🌈\nSecond line');expect(d.warnings.join(' ')).toContain('overlapping');});
 it('parses WebVTT comments and timing',()=>{const d=parseSubtitles(bytes('example.vtt').toString('utf8'),'vtt');expect(d.cues.length).toBe(1);expect(d.cues[0].end).toBe(2500);});
 it('retains ASS styles/raw comma text with no effects execution',()=>{const d=parseSubtitles(bytes('example.ass').toString('utf8'),'ass');expect(d.cues[0].text).toBe('Hello, world\n科研');expect(d.styles).toContain('Style: Default,Arial');expect(d.cues[0].raw).toContain('{\\b1}');});
 it('distinguishes MicroDVD from VobSub and refuses inferred FPS',()=>{expect(parseSubtitles(bytes('example.sub').toString('utf8'),'sub').cues[0].start).toBe(1000);expect(()=>parseSubtitles('{25}{50}hi','sub')).toThrow('frame rate');expect(()=>parseSubtitles('VobSub image binary','sub')).toThrow('variant');});
 it('empty, illegal times, length limit and sorting',()=>{expect(parseSubtitles('','srt').cues).toEqual([]);expect(parseSubtitles('1\n00:99:01,000 --> 00:00:03,000\nbad','srt').warnings.join(' ')).toContain('invalid');expect(()=>parseSubtitles('x'.repeat(4*1024*1024+1),'srt')).toThrow('Limit');});
});
it('bounded PCM waveform without AudioContext or full PCM caching',async()=>{const b=readFileSync('test-fixtures/media/audio/basic.wav');const source=new MemoryFileSource(new Blob([b]));const result=await sampleWaveform(source,new AbortController().signal);expect(result.peaks.length).toBeLessThanOrEqual(256);expect(result.sampledFrames).toBeLessThanOrEqual(16384);expect(result.peaks.some(v=>v>0)).toBe(true);expect(result.duration).toBeGreaterThan(0);});
it('samples a simulated 4 GiB long WAV with bounded source reads',async()=>{const header=readFileSync('test-fixtures/media/audio/basic.wav').subarray(0,78);let consumed=0;const size=2**32-1,source=new MemoryFileSource(new Blob([header]));source.getSize=async()=>size;source.readRange=async(at,n)=>{consumed+=n;const b=new Uint8Array(n);if(at<header.length)b.set(header.subarray(at,Math.min(header.length,at+n)));return b;};const copy=new Uint8Array(header);const view=new DataView(copy.buffer);view.setUint32(4,size-8,true);for(let i=12;i+8<=copy.length;){const length=view.getUint32(i+4,true);if(new TextDecoder().decode(copy.subarray(i,i+4))==='data'){view.setUint32(i+4,size-i-8,true);break;}i+=8+length+(length%2);}source.readRange=async(at,n)=>{consumed+=n;const b=new Uint8Array(n);if(at<copy.length)b.set(copy.subarray(at,Math.min(copy.length,at+n)));return b;};const result=await sampleWaveform(source,new AbortController().signal);expect(result.duration).toBeGreaterThan(10000);expect(result.sampledFrames).toBeLessThanOrEqual(16384);expect(consumed).toBeLessThan(18*1024*1024);});
