import { t as tr, useUiLanguage as useLocale } from "../i18n";
import { useMemo, useState } from 'react';
import { Plus, Search } from 'lucide-react';
import { Button, IconButton, Input, SearchInput, Select, Dropdown, Checkbox, Radio, Switch, Tabs, SegmentedControl, Badge, Tooltip, Separator, Progress, Skeleton, Card, Panel, EmptyState, ScrollArea } from '../components/common/ui';
import { PrismTitleBar } from '../components/shell/PrismTitleBar';
import { BrandLogo, FileIcon } from './Brand';
import { semanticColors } from './tokens';
import { useTheme, type ThemePreference } from '../hooks/useTheme';
import { setUiLanguage, useUiLanguage, type UiLanguage } from './locale';
import './showcase.css';
import {VirtualGridFixture} from './VirtualGridFixture';
/** Development-only route, removed from the production entry by Vite's DEV branch. */
export function Showcase() {
  useLocale();
    const { theme, setTheme } = useTheme(), language = useUiLanguage(), zh = language === 'zh';
    const [enabled, setEnabled] = useState(true), [tab, setTab] = useState('browse'), [count, setCount] = useState(0);
    const t = (en: string, cn: string) => zh ? cn : en;
    const options = [{ id: 'browse', label: t('Browse', '浏览') }, { id: 'standard', label: t('Standard', '标准') }, { id: 'focus', label: t('Focus', '专注') }, { id: 'disabled', label: t('Unavailable', '不可用'), disabled: true }];
    const items = useMemo(() => [{ id: 'first', label: language === 'zh' ? '增加演示计数' : 'Increment demo counter', onSelect: () => setCount(v => v + 1) }, { id: 'disabled', label: language === 'zh' ? '不可用' : 'Unavailable', disabled: true, onSelect: () => { } }, { id: 'reset', label: language === 'zh' ? '重置计数' : 'Reset counter', onSelect: () => setCount(0) }], [language]);
    return <div className="showcase-shell"><PrismTitleBar title={t('Design System · Development only', '设计系统 · 仅供开发验证')}/><main className="showcase">
  <header className="showcase-heading"><div className="showcase-brand"><BrandLogo height={48}/></div><div><h1>{t('UI Components', '基础界面组件')}</h1><p>{t('Design System & Window Chrome · Module 24', '视觉系统与窗口外观 · Module 24')}</p></div><label>{t('Theme', '主题')}<Select aria-label={tr("Theme")} value={theme} onChange={e => setTheme(e.target.value as ThemePreference)}><option value="light">{tr("Light")}</option><option value="dark">{tr("Dark")}</option><option value="system">{tr("System")}</option></Select></label><label>{t('Language', '语言')}<Select aria-label={tr("Language")} value={language} onChange={e => setUiLanguage(e.target.value as UiLanguage)}><option value="en">{tr("English")}</option><option value="zh">{tr("简体中文")}</option></Select></label></header>
  <Panel><h2>{t('Color & Typography', '颜色与字体')}</h2><div className="showcase-palette">{Object.entries(semanticColors.light).filter(([name]) => !name.includes('shadow')).map(([name]) => <div key={name}><span style={{ background: `var(--${name})` }}/><code>{name}</code></div>)}</div><div className="showcase-types">{['display', 'heading', 'subheading', 'body', 'caption', 'code', 'metadata'].map(role => <div className={`type-${role}`} key={role}>{role} {' '}{tr("· Elorin 文件查看器")}</div>)}</div></Panel>
  <Panel><h2>{t('Action Controls', '操作控件')}</h2><p>{t('Demo actions change the counter; no source files are modified.', '演示操作仅改变计数，不修改文件。')} <output aria-label={tr("Demo counter")}>{count}</output></p><div className="showcase-row"><Button variant="primary" onClick={() => setCount(v => v + 1)}><Plus size={16}/>{t('Increment', '增加计数')}</Button><Button onClick={() => setCount(0)}>{t('Reset', '重置')}</Button><Button variant="tertiary" onClick={() => setCount(v => v + 1)}>{t('Tertiary', '轻量按钮')}</Button><Button variant="danger" onClick={() => setCount(0)}>{t('Clear counter', '清除计数')}</Button><Button disabled>{t('Disabled', '不可用')}</Button><Button loading>{t('Loading…', '加载中…')}</Button><Tooltip label={t('Increment counter', '增加计数')}><IconButton aria-label={t('Add one', '增加一次')} onClick={() => setCount(v => v + 1)}><Plus size={18}/></IconButton></Tooltip><Dropdown label={t('Demo menu', '演示菜单')} items={items}/></div><Separator />
   <div className="showcase-row"><Input aria-label={t('Example input', '示例输入框')} placeholder={t('Enter a value', '请输入内容')}/><Input aria-label={t('Invalid input', '无效输入')} invalid defaultValue={t('Invalid value', '无效值')}/><Input disabled aria-label={t('Disabled input', '不可用输入框')} placeholder={t('Disabled', '不可用')}/><Select aria-label={t('Example select', '示例选择')}><option>{t('Fit to window', '适应窗口')}</option><option>100%</option></Select><SearchInput aria-label={t('Search example', '搜索示例')} placeholder={t('Search files, content, or folders…', '搜索文件、内容或文件夹…')}/></div>
   <div className="showcase-row"><Switch checked={enabled} onCheckedChange={setEnabled}>{t('Show sidebar', '显示侧边栏')}</Switch><Switch checked={false} disabled onCheckedChange={() => { }}>{t('Disabled switch', '不可用开关')}</Switch><Checkbox defaultChecked>{t('Selected', '已选中')}</Checkbox><Checkbox>{t('Not selected', '未选中')}</Checkbox><Checkbox disabled>{t('Unavailable', '不可用')}</Checkbox><Radio name="showcase-radio" defaultChecked>{t('Option one', '选项一')}</Radio><Radio name="showcase-radio">{t('Option two', '选项二')}</Radio></div>
   <div className="showcase-row"><Tabs options={options} value={tab} onChange={setTab} label={t('View tabs', '视图标签')}/><SegmentedControl options={options.slice(0, 3)} value={tab} onChange={setTab} label={t('View mode', '视图模式')}/></div>
   <div className="showcase-row">{(['neutral', 'accent', 'success', 'warning', 'danger'] as const).map(tone => <Badge tone={tone} key={tone}>{tone}</Badge>)}{['pdf', 'png', 'mp4', 'csv', 'zip', 'tsx'].map(extension => <FileIcon extension={extension} label={extension} key={extension}/>)}</div>
  </Panel>
  <Panel><h2>{t('Native Scroll System', '原生滚动系统')}</h2><p>{t('Wheel, keyboard and draggable native thumbs. These finite samples are not a virtual file model.', '支持滚轮、键盘与原生滑块拖动。以下是有限示例，不代表虚拟文件的逻辑长度。')}</p><div className="showcase-scrolls">{(['minimal', 'reading', 'data'] as const).map(variant => <Card key={variant}><h3>{variant}</h3><ScrollArea variant={variant} aria-label={tr("{v0} scroll sample", { v0: variant })}><div className={variant === 'data' ? 'showcase-wide' : undefined}>{Array.from({ length: 120 }, (_, i) => <div className="showcase-scroll-row" key={i}>{variant === 'data' ? tr("{v0}  |  45 4C 4F 52 49 4E  ·  Elorin data column  ·  文件数据示例 — horizontal scroll", { v0: String(i).padStart(8, '0') }) : tr("{v0}. Elorin · {v1}", { v0: i + 1, v1: t('A focused reading experience', '清晰、专注的阅读体验') })}</div>)}</div></ScrollArea></Card>)}</div></Panel>
  <Panel><h2>{t('Huge Virtual Grid','大型虚拟网格')}</h2><VirtualGridFixture/></Panel>
  <Panel><h2>{t('Feedback & Surfaces', '反馈与容器')}</h2><div className="showcase-feedback"><Card><h3>{t('Progress', '进度')}</h3><Progress value={62} label={t('Example progress', '示例进度')}/><Skeleton style={{ height: 20, marginTop: 16 }}/><p>{t('Static skeleton respects reduced motion.', '静态骨架屏遵循减少动态效果设置。')}</p></Card><Card><EmptyState title={t('No files yet', '尚无文件')} description={t('This is a component demonstration.', '此处仅展示基础组件。')} action={<Button onClick={() => setCount(v => v + 1)}><Search size={16}/>{t('Try demo action', '体验演示操作')}</Button>}/></Card></div></Panel>
 </main></div>;
}
