import { t as tr, useUiLanguage as useLocale } from "../../i18n";
import { useEffect, useState } from 'react';
import { Folder, Star, Search, Trash2 } from 'lucide-react';
import type { RouteId } from '../../app/routes';
import { recentFilesService, type RecentFile, type RecentFilesService } from '../../services/recentFiles';
import { favoritesService } from '../../services/favorites';
import { formatIconClass } from '../../formats/presentation';
import { relativeTime } from './Home';
const extensionGroups:Partial<Record<RouteId,RegExp>>={documents:/^(pdf|docx?|odt|rtf|epub|eml|msg)$/i,images:/^(png|jpe?g|webp|gif|svg|bmp|ico|tiff?|avif|hei[cf])$/i,data:/^(csv|tsv|xlsx?|xlsm|xlsb|ods|parquet|arrow|feather|h5|hdf5|nc|mat|sqlite|db)$/i,presentations:/^(pptx?|pptm|ppsx|potx|odp)$/i,media:/^(mp[34]|wav|flac|aac|m4a|ogg|opus|wma|avi|mov|mkv|webm|srt|vtt|ass|ssa)$/i,archives:/^(zip|tar|gz|tgz|7z|rar|bz2|xz|zst)$/i,geometry:/^(glb|gltf|stl|obj|ply|step|stp|iges|igs|dxf|dwg|fbx|dae|usd[azc]?)$/i};
export function FileLibrary({route,title,openFile,openRecent,onError,recentService=recentFilesService}:{route:RouteId;title:string;openFile:()=>void;openRecent:(path:string)=>void;onError:(error:string)=>void;recentService?:RecentFilesService}){
  useLocale();
 const [files,setFiles]=useState<RecentFile[]>([]),[favorites,setFavorites]=useState<RecentFile[]>([]),[query,setQuery]=useState('');
 useEffect(()=>{let live=true;const load=()=>void Promise.all([recentService.list(),favoritesService.list()]).then(([f,s])=>{if(live){setFiles(f);setFavorites(s);}},e=>{if(live)onError(String(e));});load();window.addEventListener('elorin-recent-change',load);window.addEventListener('elorin-favorites-change',load);return()=>{live=false;window.removeEventListener('elorin-recent-change',load);window.removeEventListener('elorin-favorites-change',load);};},[recentService,onError]);
 const visible=(route==='favorites'?favorites:files).filter(f=>!extensionGroups[route]||extensionGroups[route]!.test(f.extension)).filter(f=>route!=='code'||!Object.values(extensionGroups).some(re=>re?.test(f.extension))).filter(f=>(f.name+' '+f.path).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <section className="file-library"><header><div><h1>{title}</h1><p>{route==='favorites'?tr("Your saved file shortcuts."):tr("Files opened in Elorin. This list does not scan your disk.")}</p></div><button className="button primary" onClick={openFile}><Folder size={18}/>{tr("Open File")}</button></header><label className="library-search"><Search size={18}/><input aria-label={tr("Filter files")} placeholder={tr("Search this list…")} value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="library-file-list">{visible.map(f=><div className="library-file-row" key={f.path}><span className={formatIconClass(f.name,f.extension)}/><button onClick={()=>openRecent(f.path)}><strong>{f.name}</strong><small>{f.path}</small></button><time>{relativeTime(f.lastOpened)}</time><button aria-label={tr("{v0} {v1}", { v0: tr(favorites.some(v=>v.path===f.path)?'Remove favorite':'Add favorite'), v1: f.name })} aria-pressed={favorites.some(v=>v.path===f.path)} onClick={()=>void favoritesService.toggle(f).catch(e=>onError(String(e)))}><Star size={20} fill={favorites.some(v=>v.path===f.path)?'currentColor':'none'}/></button></div>)}{!visible.length&&<div className="library-empty"><Folder size={44}/><h2>{tr("No files here yet")}</h2><p>{tr("Open a file, or try another search.")}</p><button className="button primary" onClick={openFile}>{tr("Open File")}</button></div>}</div><footer><span>{visible.length} {' '}{tr("items")}</span>{route==='recents'&&<button onClick={()=>void recentFilesService.clear().catch(e=>onError(String(e)))}><Trash2 size={14}/>{tr("Clear Recent Files")}</button>}</footer></section>;
}
