import { t as tr, useUiLanguage as useLocale } from "../../i18n";
import { useEffect, useLayoutEffect, useRef, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { X, Pin, GripHorizontal } from 'lucide-react';
interface Layer { id: symbol; close: () => void; pinned: () => boolean }
const layers:Layer[]=[];
type SavedLayer={left:number;top:number;pinned:boolean;collapsed:boolean};
const objectLayouts=new WeakMap<object,Map<string,SavedLayer>>(),stringLayouts=new Map<string,Map<string,SavedLayer>>();
function layouts(owner:object|string){if(typeof owner==='object'){let value=objectLayouts.get(owner);if(!value){value=new Map();objectLayouts.set(owner,value);}return value;}let value=stringLayouts.get(owner);if(!value){if(stringLayouts.size>=32)stringLayouts.delete(stringLayouts.keys().next().value!);value=new Map();stringLayouts.set(owner,value);}return value;}
export function clampPanel(left:number,top:number,width:number,height:number,viewportWidth=innerWidth,viewportHeight=innerHeight){return {left:Math.max(8,Math.min(left,Math.max(8,viewportWidth-width-16))),top:Math.max(40,Math.min(top,Math.max(40,viewportHeight-height-16)))};}
export function FloatingPanel({title,owner,close,children,anchor,initial,width=330}: {title:string;owner:object|string;close:()=>void;children:ReactNode;anchor?:DOMRect;initial?:{left:number;top:number};width?:number}){
  useLocale();
 const saved=layouts(owner).get(title);
 const panel=useRef<HTMLDivElement>(null),returnFocus=useRef<HTMLElement|null>(null),callback=useRef(close),pinnedRef=useRef(saved?.pinned??false),[pinned,setPinned]=useState(saved?.pinned??false),[collapsed,setCollapsed]=useState(saved?.collapsed??false),[position,setPosition]=useState(saved?{left:saved.left,top:saved.top}:initial??{left:anchor?.left??Math.max(8,innerWidth-width-24),top:anchor?.bottom??100});const drag=useRef<{x:number;y:number;left:number;top:number} | undefined>(undefined);callback.current=close;
 useEffect(()=>{layouts(owner).set(title,{...position,pinned,collapsed});},[owner,title,position,pinned,collapsed]);
 useEffect(()=>{const id=Symbol(title);returnFocus.current=document.activeElement as HTMLElement;const layer={id,close:()=>callback.current(),pinned:()=>pinnedRef.current};layers.push(layer);const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&layers.at(-1)?.id===id&&!document.querySelector('[role="dialog"],[role="alertdialog"]')){e.preventDefault();e.stopImmediatePropagation();callback.current();}};const outside=(e:PointerEvent)=>{if(layers.at(-1)?.id===id&&!pinnedRef.current&&!panel.current?.contains(e.target as Node)&&!(e.target as Element).closest('[data-floating-trigger]'))callback.current();};window.addEventListener('keydown',key,true);window.addEventListener('pointerdown',outside);panel.current?.focus();return()=>{const index=layers.findIndex(l=>l.id===id);if(index>=0)layers.splice(index,1);window.removeEventListener('keydown',key,true);window.removeEventListener('pointerdown',outside);if(returnFocus.current?.isConnected)returnFocus.current.focus();};},[owner]);
 useLayoutEffect(()=>{const clamp=()=>{const rect=panel.current?.getBoundingClientRect();if(rect)setPosition(v=>clampPanel(v.left,v.top,rect.width,rect.height));};clamp();window.addEventListener('resize',clamp);return()=>window.removeEventListener('resize',clamp);},[]);
 return createPortal(<div ref={panel} role="region" aria-label={title} tabIndex={-1} className="floating-panel" style={{...position,width}}><header tabIndex={0} aria-label={tr("Move {v0} with arrow keys", { v0: title })} onKeyDown={e=>{const delta={ArrowLeft:[-16,0],ArrowRight:[16,0],ArrowUp:[0,-16],ArrowDown:[0,16]}[e.key as 'ArrowLeft'];if(!delta||e.target!==e.currentTarget)return;e.preventDefault();const r=panel.current!.getBoundingClientRect();setPosition(clampPanel(position.left+delta[0],position.top+delta[1],r.width,r.height));}} onPointerDown={e=>{if(e.button!==0||(e.target as Element).closest('button,input,select'))return;e.preventDefault();e.stopPropagation();drag.current={x:e.clientX,y:e.clientY,...position};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d)return;const r=panel.current!.getBoundingClientRect();setPosition(clampPanel(d.left+e.clientX-d.x,d.top+e.clientY-d.y,r.width,r.height));}} onPointerUp={()=>{drag.current=undefined;}} onPointerCancel={()=>{drag.current=undefined;}} onLostPointerCapture={()=>{drag.current=undefined;}}><GripHorizontal size={15}/><strong>{title}</strong><button aria-label={tr("{v0} {v1}", { v0: tr(collapsed?'Expand':'Collapse'), v1: title })} aria-expanded={!collapsed} onClick={()=>setCollapsed(v=>!v)}>{collapsed?'+':'−'}</button><button aria-label={tr("Pin {v0}", { v0: title })} aria-pressed={pinned} onClick={()=>{pinnedRef.current=!pinned;setPinned(!pinned);}}><Pin size={14}/></button><button aria-label={tr("Close {v0}", { v0: title })} onClick={close}><X size={15}/></button></header><div className="floating-panel-content" hidden={collapsed}>{children}</div></div>,document.body);
}
