import { useEffect } from 'react';
import { t, useUiLanguage } from '../../i18n';
import { useUiSettings } from '../../platform/ui-settings';
export function thumbMetrics(viewport:number,content:number,offset:number,track:number){const max=Math.max(0,content-viewport),size=Math.min(track,Math.max(24,track*(content?viewport/content:1))),travel=Math.max(0,track-size);return{max,size,travel,position:max?Math.max(0,Math.min(max,offset))/max*travel:0};}
const selector='.sidebar,.settings-nav,.settings-page,.viewer-scroll,.viewer-panel,.pdf-viewport,.pdf-thumbnails,.pdf-outline,.text-viewport,.markdown-reader,.markdown-source,.json-tree,.json-source,.csv-grid,.m10-grid,.archive-list,.archive-results,.geometry-tree,.data-tree,.data-grid,.m11-reading,.floating-panel-content,.top-file-tabs';
/** One event-driven system, attached to existing scroll owners; never adds a second scroller. */
export function ScrollbarSystem(){const preferences=useUiSettings(),language=useUiLanguage();useEffect(()=>{
 const forced=matchMedia('(forced-colors: active)');if(forced.matches)return;
 const owners=new Map<HTMLElement,()=>void>();let frame=0,closed=false;
 const attach=(element:HTMLElement)=>{
  const nodes=(['y','x'] as const).map(axis=>{const track=document.createElement('div'),thumb=document.createElement('span');track.className=`art-scrollbar art-scrollbar-${axis}`;track.dataset.overlayScrollbar='true';track.setAttribute('role','scrollbar');track.setAttribute('aria-orientation',axis==='y'?'vertical':'horizontal');track.setAttribute('aria-label',`${element.getAttribute('aria-label')??t('File preview')} ${t(axis==='y'?'Vertical scroll':'Horizontal scroll')}`);track.setAttribute('aria-valuemin','0');track.tabIndex=0;track.appendChild(thumb);document.body.appendChild(track);return{axis,track,thumb,drag:undefined as {start:number;offset:number}|undefined};});
  const update=()=>{const rect=element.getBoundingClientRect(),hidden=!!element.closest('[hidden]')||document.hidden||rect.width===0||rect.height===0;for(const node of nodes){const vertical=node.axis==='y',viewport=vertical?element.clientHeight:element.clientWidth,content=vertical?element.scrollHeight:element.scrollWidth,offset=vertical?element.scrollTop:element.scrollLeft,trackLength=vertical?rect.height:rect.width,metrics=thumbMetrics(viewport,content,offset,trackLength);const scrollable=metrics.max>1;node.track.hidden=hidden||!scrollable;node.track.style.left=(vertical?rect.right-14:rect.left)+'px';node.track.style.top=(vertical?rect.top:rect.bottom-14)+'px';node.track.style.width=(vertical?14:rect.width)+'px';node.track.style.height=(vertical?rect.height:14)+'px';node.track.setAttribute('aria-valuemax',String(metrics.max));node.track.setAttribute('aria-valuenow',String(Math.round(offset)));node.thumb.style[vertical?'height':'width']=metrics.size+'px';node.thumb.style.transform=vertical?`translateY(${metrics.position}px)`:`translateX(${metrics.position}px)`;}};
  const observe=new ResizeObserver(update);observe.observe(element);if(element.firstElementChild)observe.observe(element.firstElementChild);
  const releases:(()=>void)[]=[];
  for(const node of nodes){const vertical=node.axis==='y';const set=(value:number)=>{if(vertical)element.scrollTop=value;else element.scrollLeft=value;update();};const coordinate=(e:PointerEvent)=>vertical?e.clientY:e.clientX;const metrics=()=>thumbMetrics(vertical?element.clientHeight:element.clientWidth,vertical?element.scrollHeight:element.scrollWidth,vertical?element.scrollTop:element.scrollLeft,vertical?element.getBoundingClientRect().height:element.getBoundingClientRect().width);
   const down=(e:PointerEvent)=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();const m=metrics();if(e.target!==node.thumb){const r=node.track.getBoundingClientRect(),at=coordinate(e)-(vertical?r.top:r.left);set(m.travel?(at-m.size/2)/m.travel*m.max:0);}node.drag={start:coordinate(e),offset:vertical?element.scrollTop:element.scrollLeft};node.track.dataset.dragging='true';node.track.setPointerCapture(e.pointerId);};const move=(e:PointerEvent)=>{if(!node.drag)return;const m=metrics();set(node.drag.offset+(m.travel?(coordinate(e)-node.drag.start)/m.travel*m.max:0));};const end=()=>{node.drag=undefined;delete node.track.dataset.dragging;};const key=(e:KeyboardEvent)=>{const view=vertical?element.clientHeight:element.clientWidth,current=vertical?element.scrollTop:element.scrollLeft,max=metrics().max;const value=e.key==='Home'?0:e.key==='End'?max:e.key==='PageDown'?current+view:e.key==='PageUp'?current-view:['ArrowDown','ArrowRight'].includes(e.key)?current+40:['ArrowUp','ArrowLeft'].includes(e.key)?current-40:undefined;if(value!==undefined){e.preventDefault();set(Math.max(0,Math.min(max,value)));}};node.track.addEventListener('pointerdown',down);node.track.addEventListener('pointermove',move);node.track.addEventListener('pointerup',end);node.track.addEventListener('pointercancel',end);node.track.addEventListener('lostpointercapture',end);node.track.addEventListener('keydown',key);releases.push(()=>{node.track.removeEventListener('pointerdown',down);node.track.removeEventListener('pointermove',move);node.track.removeEventListener('pointerup',end);node.track.removeEventListener('pointercancel',end);node.track.removeEventListener('lostpointercapture',end);node.track.removeEventListener('keydown',key);node.track.remove();});
  }
  const ancestorScroll=(event:Event)=>{if(event.target instanceof Element&&event.target!==element&&event.target.contains(element))update();};
  element.classList.add('art-scroll-owner');element.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);window.addEventListener('elorin-scroll-metrics',update);window.addEventListener('scroll',ancestorScroll,true);document.addEventListener('visibilitychange',update);update();return()=>{observe.disconnect();element.classList.remove('art-scroll-owner');element.removeEventListener('scroll',update);window.removeEventListener('resize',update);window.removeEventListener('elorin-scroll-metrics',update);window.removeEventListener('scroll',ancestorScroll,true);document.removeEventListener('visibilitychange',update);releases.forEach(fn=>fn());};
 };
 const refresh=()=>{frame=0;if(closed||document.hidden)return;for(const [element,release]of owners)if(!element.isConnected){release();owners.delete(element);}for(const element of document.querySelectorAll<HTMLElement>(selector))if(!owners.has(element)&&['auto','scroll'].some(value=>{const style=getComputedStyle(element);return style.overflowY===value||style.overflowX===value;}))owners.set(element,attach(element));};
 const schedule=()=>{if(!frame&&!document.hidden)frame=requestAnimationFrame(refresh);};
 const mutation=new MutationObserver(records=>{if(records.some(r=>[...r.addedNodes,...r.removedNodes].some(n=>n instanceof Element&&(n.matches(selector)||!!n.querySelector(selector)))))schedule();});mutation.observe(document.body,{childList:true,subtree:true});schedule();document.addEventListener('visibilitychange',schedule);
 return()=>{closed=true;cancelAnimationFrame(frame);mutation.disconnect();document.removeEventListener('visibilitychange',schedule);for(const release of owners.values())release();owners.clear();};
 },[preferences.scrollbar,language]);return null;}
