import { t as tr, useUiLanguage as useLocale } from "../i18n";
import { LanguageRegion } from './LanguageRegion';
import { useState } from 'react';
import { Settings, Palette, SlidersHorizontal, Focus, Layout, Folder, Edit3, Search, Columns2, Archive, Play, Code2, Table2, Box, Gauge, Cpu, HardDrive, Link, Keyboard, Accessibility, Languages, Shield, Download, RotateCcw, Info } from 'lucide-react';
import { Switch } from '../components/common/controls';
import { IntegrationSettings } from './IntegrationSettings';
import { useUiSettings, uiSettingsStore, validateUiSettings, type UiSettings } from './ui-settings';
import type { ThemePreference as Theme } from '../hooks/useTheme';
import { recentFilesService } from '../services/recentFiles';
import { documentChoice } from '../document/dialog';
import { BrandLogo } from '../design-system/Brand';
const categories=[['General',Settings],['Appearance',Palette],['Viewer Behavior',SlidersHorizontal],['Focus View',Focus],['Tabs & Workspace',Layout],['File Opening',Folder],['Default Layout & Panels',Layout],['Editing Preferences',Edit3],['Search & Find',Search],['Compare',Columns2],['Archive Viewer',Archive],['Media Viewer',Play],['Code / Text Viewer',Code2],['Spreadsheet Viewer',Table2],['3D / CAD Viewer',Box],['Performance',Gauge],['Hardware Acceleration',Cpu],['Cache & Temporary Files',HardDrive],['File Associations',Link],['Keyboard Shortcuts',Keyboard],['Accessibility',Accessibility],['Language & Region',Languages],['Privacy & Local Data',Shield],['Updates',Download],['Backup / Reset / Diagnostics',RotateCcw],['About Elorin',Info]] as const;
const unsupported:Record<string,string[]>={General:['Start Elorin','Default view mode','Check for updates','Show system notifications'],'Viewer Behavior':['Default zoom level','Image fit mode','Smooth zooming','Remember zoom level per file','Enable mouse wheel zoom','Page navigation'],'File Opening':['Open supported files in','Open folders in','Handle unsupported files','Ask before opening large files','Remember last folder','Open all files in the same tab'],Compare:['Default compare mode','Ignore whitespace differences','Ignore line ending differences','Highlight word-level changes','Show difference overlay'],'Archive Viewer':['Default extract location','Ask before extracting large archives','Show compression ratio'],'Media Viewer':['Default video quality','Enable slideshow','Slideshow interval','Hardware acceleration for video'],'Spreadsheet Viewer':['Default zoom','Default column visibility','Formula recalculation'],'3D / CAD Viewer':['Default projection','Default quality preset','Default units'],Performance:['Memory budget across all viewers','Background task limit'],'Hardware Acceleration':['Hardware rendering policy','Video decoder selection'],'Cache & Temporary Files':['Combined cache budget','Clear active viewer caches'],Updates:['Check for updates','Download updates in background','Notify when updates are available'],'Language & Region':['Date format','Time format','Number format','First day of week'], 'Editing Preferences':['Default text encoding','Auto-detect encoding','Insert spaces instead of tabs','Auto save changes'],'Search & Find':['Default search location','Search in subfolders','Use regular expressions across all formats','Maximum search results','File types to include']};
export function SettingsCenter({theme,setTheme,onError}:{theme:Theme;setTheme:(value:Theme)=>void;onError:(message:string)=>void}){
  useLocale();
 const [section,setSection]=useState('General'),[message,setMessage]=useState('');const settings=useUiSettings();
 const update=(patch:Partial<UiSettings>)=>void uiSettingsStore.update(patch).then(()=>setMessage(tr("Settings saved.")),e=>onError(tr(e instanceof Error ? e.message : String(e))));
 const toggle=(key:keyof UiSettings,label:string,hint?:string)=><div className="setting-row" key={key}><span>{tr(label)}{hint&&<small>{tr(hint)}</small>}</span><Switch checked={settings[key]===true} onCheckedChange={v=>update({[key]:v})}>{tr(label)}</Switch></div>;
 const select=(key:keyof UiSettings,label:string,options:(string|number)[],labels?:string[])=><label className="setting-row" key={key}><span>{tr(label)}</span><select aria-label={tr(label)} value={String(settings[key])} onChange={e=>update({[key]:typeof settings[key]==='number'?Number(e.target.value):e.target.value})}>{options.map((v,i)=><option value={v} key={v}>{typeof v === 'number' ? v : tr(labels?.[i]??v)}</option>)}</select></label>;
 const download=(value:unknown,name:string)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0);};
 return <section className="settings-center"><nav className="settings-nav" aria-label={tr("Settings categories")}><div className="settings-brand"><BrandLogo height={36}/></div>{categories.map(([label,Icon])=><button key={label} aria-current={section===label?'page':undefined} onClick={()=>{setSection(label);setMessage('');}}><Icon size={15}/><span>{tr(label)}</span></button>)}</nav><div className="settings-page"><header><h1>{section==='General'?tr("Settings"):tr(section)}</h1><p>{section==='General'?tr("Customize Elorin to match your workflow and preferences."):tr("Customize {v0} in Elorin.", { v0: tr(section) })}</p></header>
 <div className="settings-section"><h2>{tr(section)}</h2><p className="settings-description">{tr("Changes with an available viewer capability apply immediately.")}</p><div className="settings-card">
 {section==='General'&&<>{toggle('rememberWorkspace',tr("Remember last opened files and tabs"),'Reopen your previous session on launch.')}{toggle('showTips',tr("Show welcome tips"))}</>}
 {section==='Appearance'&&<><div className="setting-block"><h3>{tr("Theme")}</h3><div className="theme-cards">{(['light','dark','system'] as Theme[]).map(v=><button key={v} className={`theme-card ${v}`} aria-pressed={theme===v} onClick={()=>setTheme(v)}><span className="theme-mini"><i/><i/><i/></span><strong>{tr(v[0].toUpperCase()+v.slice(1))}</strong></button>)}</div></div><div className="setting-block"><h3>{tr("Accent Color")}</h3><div className="accent-options">{['#0066ff','#6256ff','#b52aff','#ff3358','#ff7a16','#ffb700','#00a69e','#00bdd4'].map(color=><button key={color} aria-label={tr("Accent {v0}", { v0: color })} aria-pressed={settings.accent===color} style={{background:color}} onClick={()=>update({accent:color})}/>)}</div></div>{select('density',tr("Interface Density"),['comfortable','compact','touch'],['Comfortable','Compact','Touch Friendly'])}</>}
 {section==='Tabs & Workspace'&&toggle('rememberWorkspace',tr("Restore workspace on launch"))}
 {section==='Focus View'&&<>{toggle('focusAutoHide',tr("Auto-hide toolbar"))}{select('focusBackground',tr("Background style"),['solid','gradient','blur'],['Solid','Gradient','Blur'])}<label className="setting-row"><span>{tr("Background color")}</span><input type="color" aria-label={tr("Focus background color")} value={settings.focusBackgroundColor} onChange={e=>update({focusBackgroundColor:e.target.value})}/></label>{toggle('focusExitOnFileClose',tr("Exit Focus View on file close"))}</>}
 {section==='Default Layout & Panels'&&<>{toggle('inspector',tr("Show Inspector panel"))}{select('statusBar',tr("Status bar"),['auto','show','hide'],['Automatic','Show','Hide'])}{select('scrollbar',tr("Scrollbar visibility"),['auto','always'],['Automatically soften','Always show'])}</>}
 {(section==='Editing Preferences'||section==='Code / Text Viewer')&&<>{toggle('textWrap',tr("Word wrap"))}{toggle('textNumbers',tr("Show line numbers"))}{select('textTabSize',tr("Tab size"),[2,4,8])}{select('textFontSize',tr("Font size"),[12,13,14,16,18,20,24])}{select('textLineHeight',tr("Line height"),[1.2,1.5,1.8,2])}<p className="settings-note">{tr("Text editing supports UTF-8 files up to 2 MiB. Saving retains the existing conflict and validation checks.")}</p></>}
 {section==='Search & Find'&&<>{toggle('searchCase',tr("Match case by default"))}{toggle('searchWhole',tr("Whole words by default"))}<p className="settings-note">{tr("Search covers the current file or open tabs. Text/Hex and document search options depend on the active viewer.")}</p></>}
 {section==='Accessibility'&&<>{select('uiScale',tr("Increase UI scale"),[80,90,100,110,125,150])}{toggle('highContrast',tr("High contrast mode"))}{toggle('reduceMotion',tr("Reduce motion"))}{toggle('largeTargets',tr("Larger click targets"))}{select('scrollbar',tr("Scrollbar visibility"),['auto','always'])}</>}
 {section==='File Associations'&&<IntegrationSettings/>}
 {section==='Keyboard Shortcuts'&&<><p className="settings-note">{tr("Current application shortcuts. Viewer shortcuts apply while its content is focused.")}</p>{[['Open File','Ctrl + O'],['New File','Ctrl + N'],['Close Tab','Ctrl + W'],['Reopen Closed Tab','Ctrl + Shift + T'],['Switch Tab','Ctrl + Tab'],['Quick Open','Ctrl + P'],['Command Palette','Ctrl + Shift + P'],['Find','Ctrl + F'],['Save','Ctrl + S']].map(([a,b])=><div className="setting-row" key={a}><span>{tr(a)}</span><kbd>{b}</kbd></div>)}</>}
 {section==='Language & Region'&&<LanguageRegion onError={onError}/>}
 {section==='Privacy & Local Data'&&<><p className="settings-note">{tr("Files remain local. Recent paths and workspace state are stored in the application data directory. No usage analytics service is enabled.")}</p><button className="button" onClick={()=>void recentFilesService.clear().then(()=>setMessage(tr("Recent files cleared.")),e=>onError(tr(e instanceof Error ? e.message : String(e))))}>{tr("Clear Recent Files")}</button></>}
 {section==='Backup / Reset / Diagnostics'&&<><div className="setting-row"><span>{tr("Export Settings")}<small>{tr("Export the validated application preferences.")}</small></span><button className="button" onClick={()=>download({version:1,ui:settings,theme},'elorin-settings.json')}>{tr("Export Settings")}</button></div><label className="setting-row"><span>{tr("Import Settings")}</span><input aria-label={tr("Import Settings")} type="file" accept=".json" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.size>65536){onError(tr('Settings import is limited to 64 KiB.'));return;}void f.text().then(async text=>{const value=JSON.parse(text);if(value.version!==1||!value.ui)throw Error('Unsupported settings file');await uiSettingsStore.update(validateUiSettings(value.ui));if(['light','dark','system'].includes(value.theme))setTheme(value.theme);setMessage(tr("Settings imported."));}).catch(e=>onError(tr(e instanceof Error ? e.message : String(e))));}}/></label><div className="setting-row"><span>{tr("Reset Settings")}</span><button className="button" onClick={()=>void documentChoice(tr("Reset application preferences? Your files and favorites are retained."),['Reset','Cancel']).then(async choice=>{if(choice==='Reset'){await uiSettingsStore.reset();setTheme('system');setMessage(tr("Settings reset."));}}).catch(e=>onError(tr(e instanceof Error ? e.message : String(e))))}>{tr("Reset Settings")}</button></div><div className="setting-row"><span>{tr("Diagnostics")}</span><button className="button" onClick={()=>download({version:1,platform:navigator.platform,userAgent:navigator.userAgent,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},settings},'elorin-diagnostics.json')}>{tr("Generate Report")}</button></div></>}
 {section==='About Elorin'&&<div className="about-brand"><BrandLogo height={92}/><p>{tr("Version 0.1.0")}</p><p>{tr("A unified file viewer for a simpler,")}<br/>{tr("more focused workflow.")}</p></div>}
 {(unsupported[section]??[]).map(label=><div className="setting-row unavailable-setting" key={label}><span>{tr(label)}<small>{tr("This capability is not available yet.")}</small></span><button role="switch" aria-checked={false} disabled aria-label={tr(label)} className="ds-switch"><span className="ds-switch-track"><span/></span></button></div>)}
 </div></div>{message&&<p className="settings-feedback" role="status">{tr(message)}</p>}</div></section>;
}
